[mcp_servers.msw-maker-mcp]
command = "cmd.exe"
args = ["/c", "call", "C:\\Users\\zsp22\\AppData\\Local\\Nexon\\MapleStory Worlds\\MakerMCP\\msw-maker-mcp.bat"]

[mcp_servers.msw-mcp]
url = "https://msw-mcp.nexon.com/mcp"
http_headers = { "Authorization" = "Bearer 7b4af764aea248ea99f08ff7def03b57" }
